apiVersion: v1
kind: ServiceAccount
metadata:
  name: podinfo-ts
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: podinfo-ts:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: podinfo-ts
  namespace: default
---
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: podinfo-ts
  namespace: default
spec:
  serviceAccountName: podinfo-ts
  projectRepo: https://github.com/pulumi-initech/podinfo-ts
  branch: main
  shallow: true
  stack: dev
  refresh: true
  destroyOnFinalize: true
  envRefs:
    PULUMI_ACCESS_TOKEN:
      type: Secret
      secret:
        name: pulumi-access-token
        key: PULUMI_ACCESS_TOKEN
  workspaceTemplate:
    spec:
      image: pulumi/pulumi:3.197.0-nonroot

